#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd)

echo "=================================="
echo "Installing rodionovd's .dotfiles  "
echo "=================================="

sh "$DOTFILES_ROOT/git/git.sh"
sh "$DOTFILES_ROOT/brew.sh"
sh "$DOTFILES_ROOT/cask/cask.sh"
sh "$DOTFILES_ROOT/iterm2/iterm2.sh"
sh "$DOTFILES_ROOT/atom/atom.sh"
sh "$DOTFILES_ROOT/vim/vim.sh"
sh "$DOTFILES_ROOT/zsh/zsh.sh"
sh "$DOTFILES_ROOT/pip.sh"
sh "$DOTFILES_ROOT/osx.sh"

echo "=================================="
echo "Done. Have a nice day!            "
echo "=================================="
