#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd)

echo "=================================="
echo "Installing rodionovd's .dotfiles  "
echo "=================================="

sh "$DOTFILES_ROOT/zsh/zsh.sh"
sh "$DOTFILES_ROOT/vim/vim.sh"
sh "$DOTFILES_ROOT/git/git.sh"
sh "$DOTFILES_ROOT/pip.sh"
sh "$DOTFILES_ROOT/gems.sh"
sh "$DOTFILES_ROOT/xcode/xcode.sh"
sh "$DOTFILES_ROOT/iterm2/iterm2.sh"
sh "$DOTFILES_ROOT/atom/atom.sh"
sh "$DOTFILES_ROOT/hammerspoon/hammerspoon.sh"

sh "$DOTFILES_ROOT/osx.sh"
sh "$DOTFILES_ROOT/fonts/fonts.sh"

# Install my private dotfiles as well
if [[ "$USER" == "rodionovd" ]]; then
    git clone git@github.com:rodionovd/dotfiles-private.git
    (cd /.dotfiles-private && ./bootstrap)
fi

echo "============================================="
echo "Don't forget to run ./after_xcode_install.sh "
echo "when you install Xcode                     :)"
echo "============================================="
