# Sources
tap 'homebrew/core'
tap 'homebrew/bundle' # for Brewfile
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/boneyard' # for class-dump
tap 'rodionovd/taps' # for shortcuts

# Runtimes
brew 'python'
brew 'ruby'
brew 'openjdk'

# Utils
brew 'carthage'
brew 'class-dump', args: ['HEAD']
brew 'cocoapods'
brew 'fastlane'
brew 'git'
brew 'sqlite'
brew 'youtube-dl'

# Apps
cask '0xed'
cask '1password'
cask 'alfred'
cask 'apparency'
cask 'blockblock'
cask 'coderunner'
cask 'day-o'
cask 'github'
cask 'hopper-disassembler'
cask 'iterm2'
cask 'marked'
cask 'microsoft-teams'
cask 'monodraw'
cask 'paw'
cask 'pixelsnap'
cask 'sketch'
cask 'slack'
cask 'sublime-merge'
cask 'suspicious-package'
cask 'telegram'
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'vlc'

# Fonts
cask 'font-hack'
