#! /bin/bash
# alias: brew cl
#
# This is a Homebrew alias script. It'll be called when the user
# types `brew cl`. Any remaining arguments are passed to
# this script. You can retrieve those with $*, or only the first
# one with $1. Please keep your script on one line.
brew cleanup --prune=all
