#! /bin/bash
# alias: brew use
#
# This is a Homebrew alias script. It'll be called when the user
# types `brew use`. Any remaining arguments are passed to
# this script. You can retrieve those with $*, or only the first
# one with $1. Please keep your script on one line.
brew uses --installed --recursive $1
