#
# Locale
#
export LC_CTYPE="UTF-8"
export LANG=en_US.UTF-8

#
# Opt-outs
#
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_AUTO_UPDATE=1

# 
# oh-my-zsh configuration
# 
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="rodionovd"
ZSH_COMPDUMP="$ZSH_CACHE_DIR/.zcompdump"

# Disable auto-updates but keep periodic reminders
zstyle ':omz:update' mode reminder

plugins=()
source $ZSH/oh-my-zsh.sh

#
# Various autocomplete options

# killall autocomplete
zstyle ':completion:*:processes' command 'ps -ax'
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;32'
zstyle ':completion:*:kill:*'   force-list always
zstyle ':completion:*:processes-names' command 'ps -e -o comm='
zstyle ':completion:*:killall:*'   force-list always

#
# Add some colors for man(1)
#
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# 
# PATH
# 
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/usr/local/sbin"
eval "$(/opt/homebrew/bin/brew shellenv)"
